### ISSUE TITLE
Contributing to this Open Source Project

### ISSUE THREAD

**Issue by noahweasley** [solidtm/NoteKeeper#1]
Hi, am Noah. I was going through your Github profile and saw that you just started learning Android Development. Although, I just started using Github, am an experienced Android Engineer. I would like to participate in this your project. I have a similar project I, myself want to start. If it's a good idea, contact me or rather add me as a collaborator to this project. Thanks.

**Comment by solidtm** [comment]
Hi Noah, I'm Richard.

I'm glad you have shown interests in this project. I can understand how daunting it is in GitHub for starters, but that not withstanding I'm a starter too. I just started learning android development and would definitely love to collaborate with you on this project. Do find the mail inviting you to collaborate 

Thanks.
